name: Second Workflow

on:
  repository_dispatch:
    types: [trigger-grafana]

jobs:
  triggered-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Run after first workflow
        run: echo "Triggered by First Workflow completion"
